#!/usr/bin/env python3
"""
Generate Excel file with 20 Egyptian medical products for POC
"""

import pandas as pd
from openpyxl import Workbook
from openpyxl.styles import Font, PatternFill, Alignment, Border, Side
import json
from datetime import datetime, timedelta
import random

# Generate 20 realistic Egyptian medical products
products_data = [
    # Pain Relief & Fever (1-3)
    {
        "product_code": "MED-001-BRUF",
        "name_en": "Brufen 400mg Tablets",
        "name_ar": "بروفين 400 مجم أقراص",
        "description_en": "Anti-inflammatory pain relief tablets. Effective for arthritis, dental pain, and fever reduction.",
        "description_ar": "أقراص مضادة للالتهابات لتخفيف الألم. فعال لالتهاب المفاصل وآلام الأسنان وخفض الحرارة.",
        "category": "pain-relief",
        "subcategory": "oral-medications",
        "brand": "Abbott",
        "manufacturer": "Abbott Egypt",
        "country_of_origin": "Egypt",
        "price_per_unit": 32.50,
        "currency": "EGP",
        "unit": "box",
        "unit_size": "30 tablets",
        "stock_quantity": 450,
        "min_order_quantity": 1,
        "max_order_quantity": 10,
        "sku": "BRUF-400-30T",
        "barcode": "6221060000123",
        "hsn_code": "30049099",
        "requires_prescription": False,
        "is_controlled": False,
        "active_ingredient": "Ibuprofen 400mg",
        "dosage_form": "Tablet",
        "side_effects": "May cause stomach upset, heartburn. Take with food.",
        "contraindications": "Stomach ulcers, severe kidney or liver disease",
        "storage_conditions": "Store below 25°C in a dry place",
        "expiry_date": "2026-06-30",
        "batch_number": "B2024-101",
        "seller_code": "PHARM-001",
        "seller_name": "El-Ezaby Pharmacy",
        "delivery_method": "express",
        "delivery_days_min": 1,
        "delivery_days_max": 2,
        "delivery_fee": 35.00,
        "free_delivery_threshold": 250.00,
        "return_policy": "7 days return for unopened packages",
        "warranty_period": "N/A",
        "discount_percentage": 5,
        "tax_percentage": 14,
        "product_images": json.dumps([
            "https://example.com/brufen-1.jpg",
            "https://example.com/brufen-2.jpg",
            "https://example.com/brufen-3.jpg"
        ]),
        "specifications": json.dumps({
            "form": "Coated tablet",
            "color": "Pink",
            "package": "Blister pack"
        }),
        "tags": "pain-relief,anti-inflammatory,arthritis,fever",
        "meta_title": "Buy Brufen 400mg Online | Medicum Egypt",
        "meta_description": "Brufen 400mg anti-inflammatory tablets for pain relief. Fast delivery across Egypt.",
        "is_featured": True,
        "is_active": True,
        "weight_grams": 45,
        "dimensions_cm": "10x6x3"
    },
    {
        "product_code": "MED-002-PAND",
        "name_en": "Panadol Extra Tablets",
        "name_ar": "بانادول إكسترا أقراص",
        "description_en": "Advanced pain relief with paracetamol and caffeine. For headaches and strong pain.",
        "description_ar": "تسكين متقدم للألم مع الباراسيتامول والكافيين. للصداع والألم الشديد.",
        "category": "pain-relief",
        "subcategory": "oral-medications",
        "brand": "GSK",
        "manufacturer": "GlaxoSmithKline Egypt",
        "country_of_origin": "Egypt",
        "price_per_unit": 28.00,
        "currency": "EGP",
        "unit": "box",
        "unit_size": "24 tablets",
        "stock_quantity": 600,
        "min_order_quantity": 1,
        "max_order_quantity": 15,
        "sku": "PAND-EXT-24T",
        "barcode": "6221060000456",
        "hsn_code": "30049099",
        "requires_prescription": False,
        "is_controlled": False,
        "active_ingredient": "Paracetamol 500mg, Caffeine 65mg",
        "dosage_form": "Tablet",
        "side_effects": "Rare: nausea, insomnia due to caffeine",
        "contraindications": "Severe liver disease, caffeine sensitivity",
        "storage_conditions": "Store below 30°C",
        "expiry_date": "2026-08-15",
        "batch_number": "B2024-102",
        "seller_code": "PHARM-002",
        "seller_name": "Seif Pharmacies",
        "delivery_method": "standard",
        "delivery_days_min": 2,
        "delivery_days_max": 3,
        "delivery_fee": 30.00,
        "free_delivery_threshold": 200.00,
        "return_policy": "7 days return policy",
        "warranty_period": "N/A",
        "discount_percentage": 10,
        "tax_percentage": 14,
        "product_images": json.dumps([
            "https://example.com/panadol-extra-1.jpg",
            "https://example.com/panadol-extra-2.jpg"
        ]),
        "specifications": json.dumps({
            "form": "Caplet",
            "color": "White",
            "package": "Blister pack"
        }),
        "tags": "pain-relief,headache,paracetamol,OTC",
        "meta_title": "Buy Panadol Extra Online | Medicum Egypt",
        "meta_description": "Panadol Extra for advanced pain relief. Available for delivery across Egypt.",
        "is_featured": True,
        "is_active": True,
        "weight_grams": 40,
        "dimensions_cm": "9x6x3"
    },
    {
        "product_code": "MED-003-VOLT",
        "name_en": "Voltaren 50mg Tablets",
        "name_ar": "فولتارين 50 مجم أقراص",
        "description_en": "Diclofenac sodium for inflammation and pain. Effective for back pain and joint disorders.",
        "description_ar": "ديكلوفيناك الصوديوم للالتهاب والألم. فعال لآلام الظهر واضطرابات المفاصل.",
        "category": "pain-relief",
        "subcategory": "oral-medications",
        "brand": "Novartis",
        "manufacturer": "Novartis Egypt",
        "country_of_origin": "Egypt",
        "price_per_unit": 45.00,
        "currency": "EGP",
        "unit": "box",
        "unit_size": "20 tablets",
        "stock_quantity": 350,
        "min_order_quantity": 1,
        "max_order_quantity": 8,
        "sku": "VOLT-50-20T",
        "barcode": "6221060000789",
        "hsn_code": "30049099",
        "requires_prescription": True,
        "is_controlled": False,
        "active_ingredient": "Diclofenac sodium 50mg",
        "dosage_form": "Enteric-coated tablet",
        "side_effects": "May cause stomach upset, dizziness. Take with food.",
        "contraindications": "Stomach ulcers, heart disease, pregnancy (3rd trimester)",
        "storage_conditions": "Store below 25°C",
        "expiry_date": "2026-10-20",
        "batch_number": "B2024-103",
        "seller_code": "PHARM-001",
        "seller_name": "El-Ezaby Pharmacy",
        "delivery_method": "express",
        "delivery_days_min": 1,
        "delivery_days_max": 2,
        "delivery_fee": 35.00,
        "free_delivery_threshold": 250.00,
        "return_policy": "No returns for prescription medicines",
        "warranty_period": "N/A",
        "discount_percentage": 0,
        "tax_percentage": 14,
        "product_images": json.dumps([
            "https://example.com/voltaren-1.jpg",
            "https://example.com/voltaren-2.jpg"
        ]),
        "specifications": json.dumps({
            "form": "Enteric-coated tablet",
            "color": "Brown",
            "package": "Blister pack"
        }),
        "tags": "anti-inflammatory,arthritis,back-pain,prescription",
        "meta_title": "Voltaren 50mg Tablets | Medicum Egypt",
        "meta_description": "Voltaren 50mg for inflammation and severe pain. Prescription required.",
        "is_featured": False,
        "is_active": True,
        "weight_grams": 35,
        "dimensions_cm": "8x6x2"
    },
    
    # Antibiotics (4-6)
    {
        "product_code": "MED-004-AUGM",
        "name_en": "Augmentin 1g Tablets",
        "name_ar": "أوجمنتين 1 جم أقراص",
        "description_en": "Powerful antibiotic combination for bacterial infections. Treats respiratory and urinary infections.",
        "description_ar": "مزيج قوي من المضادات الحيوية للعدوى البكتيرية. يعالج التهابات الجهاز التنفسي والبولي.",
        "category": "antibiotics",
        "subcategory": "oral-medications",
        "brand": "GSK",
        "manufacturer": "GlaxoSmithKline Egypt",
        "country_of_origin": "Egypt",
        "price_per_unit": 89.50,
        "currency": "EGP",
        "unit": "box",
        "unit_size": "14 tablets",
        "stock_quantity": 200,
        "min_order_quantity": 1,
        "max_order_quantity": 3,
        "sku": "AUGM-1G-14T",
        "barcode": "6221060001234",
        "hsn_code": "30041090",
        "requires_prescription": True,
        "is_controlled": False,
        "active_ingredient": "Amoxicillin 875mg, Clavulanic acid 125mg",
        "dosage_form": "Film-coated tablet",
        "side_effects": "Diarrhea, nausea, skin rash. Take with food.",
        "contraindications": "Penicillin allergy, liver problems",
        "storage_conditions": "Store below 25°C in dry place",
        "expiry_date": "2025-12-31",
        "batch_number": "B2024-104",
        "seller_code": "PHARM-003",
        "seller_name": "Roshdy Pharmacies",
        "delivery_method": "standard",
        "delivery_days_min": 1,
        "delivery_days_max": 3,
        "delivery_fee": 30.00,
        "free_delivery_threshold": 300.00,
        "return_policy": "No returns for antibiotics",
        "warranty_period": "N/A",
        "discount_percentage": 0,
        "tax_percentage": 14,
        "product_images": json.dumps([
            "https://example.com/augmentin-1.jpg",
            "https://example.com/augmentin-2.jpg"
        ]),
        "specifications": json.dumps({
            "form": "Film-coated tablet",
            "color": "White",
            "package": "Blister pack"
        }),
        "tags": "antibiotic,bacterial-infection,prescription",
        "meta_title": "Augmentin 1g Antibiotic | Medicum Egypt",
        "meta_description": "Augmentin 1g powerful antibiotic. Prescription required.",
        "is_featured": False,
        "is_active": True,
        "weight_grams": 30,
        "dimensions_cm": "10x7x2"
    },
    {
        "product_code": "MED-005-ZITH",
        "name_en": "Zithromax 500mg Tablets",
        "name_ar": "زيثروماكس 500 مجم أقراص",
        "description_en": "Azithromycin antibiotic for respiratory infections. Once daily dosing for convenience.",
        "description_ar": "أزيثروميسين مضاد حيوي لالتهابات الجهاز التنفسي. جرعة واحدة يومياً للراحة.",
        "category": "antibiotics",
        "subcategory": "oral-medications",
        "brand": "Pfizer",
        "manufacturer": "Pfizer Egypt",
        "country_of_origin": "Egypt",
        "price_per_unit": 95.00,
        "currency": "EGP",
        "unit": "box",
        "unit_size": "3 tablets",
        "stock_quantity": 150,
        "min_order_quantity": 1,
        "max_order_quantity": 2,
        "sku": "ZITH-500-3T",
        "barcode": "6221060001567",
        "hsn_code": "30041090",
        "requires_prescription": True,
        "is_controlled": False,
        "active_ingredient": "Azithromycin 500mg",
        "dosage_form": "Film-coated tablet",
        "side_effects": "Stomach upset, diarrhea, headache",
        "contraindications": "Liver disease, heart rhythm problems",
        "storage_conditions": "Store below 30°C",
        "expiry_date": "2026-03-15",
        "batch_number": "B2024-105",
        "seller_code": "PHARM-002",
        "seller_name": "Seif Pharmacies",
        "delivery_method": "express",
        "delivery_days_min": 1,
        "delivery_days_max": 2,
        "delivery_fee": 35.00,
        "free_delivery_threshold": 250.00,
        "return_policy": "No returns for antibiotics",
        "warranty_period": "N/A",
        "discount_percentage": 0,
        "tax_percentage": 14,
        "product_images": json.dumps([
            "https://example.com/zithromax-1.jpg"
        ]),
        "specifications": json.dumps({
            "form": "Film-coated tablet",
            "color": "Pink",
            "package": "Blister pack"
        }),
        "tags": "antibiotic,azithromycin,respiratory,prescription",
        "meta_title": "Zithromax 500mg | Medicum Egypt",
        "meta_description": "Zithromax azithromycin antibiotic. Prescription required.",
        "is_featured": False,
        "is_active": True,
        "weight_grams": 20,
        "dimensions_cm": "8x5x2"
    },
    {
        "product_code": "MED-006-CIPR",
        "name_en": "Ciprofar 500mg Tablets",
        "name_ar": "سيبروفار 500 مجم أقراص",
        "description_en": "Ciprofloxacin for urinary tract and respiratory infections. Broad spectrum antibiotic.",
        "description_ar": "سيبروفلوكساسين لالتهابات المسالك البولية والجهاز التنفسي. مضاد حيوي واسع الطيف.",
        "category": "antibiotics",
        "subcategory": "oral-medications",
        "brand": "Pharco",
        "manufacturer": "Pharco Pharmaceuticals",
        "country_of_origin": "Egypt",
        "price_per_unit": 42.00,
        "currency": "EGP",
        "unit": "box",
        "unit_size": "10 tablets",
        "stock_quantity": 300,
        "min_order_quantity": 1,
        "max_order_quantity": 5,
        "sku": "CIPR-500-10T",
        "barcode": "6221060001890",
        "hsn_code": "30041090",
        "requires_prescription": True,
        "is_controlled": False,
        "active_ingredient": "Ciprofloxacin 500mg",
        "dosage_form": "Film-coated tablet",
        "side_effects": "Nausea, diarrhea, dizziness. Avoid sun exposure.",
        "contraindications": "Pregnancy, children under 18, tendon problems",
        "storage_conditions": "Store below 25°C",
        "expiry_date": "2026-05-20",
        "batch_number": "B2024-106",
        "seller_code": "PHARM-001",
        "seller_name": "El-Ezaby Pharmacy",
        "delivery_method": "standard",
        "delivery_days_min": 2,
        "delivery_days_max": 3,
        "delivery_fee": 30.00,
        "free_delivery_threshold": 200.00,
        "return_policy": "No returns for antibiotics",
        "warranty_period": "N/A",
        "discount_percentage": 5,
        "tax_percentage": 14,
        "product_images": json.dumps([
            "https://example.com/ciprofar-1.jpg"
        ]),
        "specifications": json.dumps({
            "form": "Film-coated tablet",
            "color": "White",
            "package": "Blister pack"
        }),
        "tags": "antibiotic,UTI,ciprofloxacin,prescription",
        "meta_title": "Ciprofar 500mg Antibiotic | Medicum Egypt",
        "meta_description": "Ciprofloxacin 500mg for bacterial infections. Prescription required.",
        "is_featured": False,
        "is_active": True,
        "weight_grams": 25,
        "dimensions_cm": "9x6x2"
    },
    
    # Vitamins & Supplements (7-9)
    {
        "product_code": "MED-007-VITD",
        "name_en": "Vitamin D3 5000 IU Capsules",
        "name_ar": "فيتامين د3 5000 وحدة دولية كبسولات",
        "description_en": "High strength Vitamin D3 for bone health and immunity. Essential for calcium absorption.",
        "description_ar": "فيتامين د3 عالي القوة لصحة العظام والمناعة. ضروري لامتصاص الكالسيوم.",
        "category": "vitamins",
        "subcategory": "supplements",
        "brand": "Mepaco",
        "manufacturer": "Mepaco Egypt",
        "country_of_origin": "Egypt",
        "price_per_unit": 55.00,
        "currency": "EGP",
        "unit": "box",
        "unit_size": "30 capsules",
        "stock_quantity": 400,
        "min_order_quantity": 1,
        "max_order_quantity": 10,
        "sku": "VITD-5000-30C",
        "barcode": "6221060002123",
        "hsn_code": "30045090",
        "requires_prescription": False,
        "is_controlled": False,
        "active_ingredient": "Cholecalciferol 5000 IU",
        "dosage_form": "Soft gelatin capsule",
        "side_effects": "Rare: hypercalcemia with excessive doses",
        "contraindications": "Hypercalcemia, kidney stones",
        "storage_conditions": "Store below 25°C, protect from light",
        "expiry_date": "2027-01-15",
        "batch_number": "B2024-107",
        "seller_code": "PHARM-003",
        "seller_name": "Roshdy Pharmacies",
        "delivery_method": "standard",
        "delivery_days_min": 1,
        "delivery_days_max": 3,
        "delivery_fee": 30.00,
        "free_delivery_threshold": 200.00,
        "return_policy": "14 days return for unopened items",
        "warranty_period": "N/A",
        "discount_percentage": 15,
        "tax_percentage": 14,
        "product_images": json.dumps([
            "https://example.com/vitamin-d-1.jpg",
            "https://example.com/vitamin-d-2.jpg"
        ]),
        "specifications": json.dumps({
            "form": "Soft gelatin capsule",
            "color": "Yellow",
            "package": "Bottle"
        }),
        "tags": "vitamin-D,bone-health,immunity,supplement",
        "meta_title": "Vitamin D3 5000 IU | Medicum Egypt",
        "meta_description": "High strength Vitamin D3 supplements for bone health and immunity.",
        "is_featured": True,
        "is_active": True,
        "weight_grams": 60,
        "dimensions_cm": "6x6x10"
    },
    {
        "product_code": "MED-008-OMEG",
        "name_en": "Omega-3 Fish Oil 1000mg",
        "name_ar": "أوميغا 3 زيت السمك 1000 مجم",
        "description_en": "Premium omega-3 fatty acids for heart and brain health. Supports cardiovascular system.",
        "description_ar": "أحماض أوميغا 3 الدهنية الممتازة لصحة القلب والدماغ. يدعم نظام القلب والأوعية الدموية.",
        "category": "vitamins",
        "subcategory": "supplements",
        "brand": "Sedico",
        "manufacturer": "Sedico Pharmaceuticals",
        "country_of_origin": "Egypt",
        "price_per_unit": 85.00,
        "currency": "EGP",
        "unit": "box",
        "unit_size": "30 capsules",
        "stock_quantity": 250,
        "min_order_quantity": 1,
        "max_order_quantity": 8,
        "sku": "OMEG-1000-30C",
        "barcode": "6221060002456",
        "hsn_code": "30045090",
        "requires_prescription": False,
        "is_controlled": False,
        "active_ingredient": "Fish Oil 1000mg (EPA 180mg, DHA 120mg)",
        "dosage_form": "Soft gelatin capsule",
        "side_effects": "Fishy aftertaste, mild stomach upset",
        "contraindications": "Fish allergy, bleeding disorders",
        "storage_conditions": "Store below 25°C, refrigerate after opening",
        "expiry_date": "2026-09-30",
        "batch_number": "B2024-108",
        "seller_code": "PHARM-002",
        "seller_name": "Seif Pharmacies",
        "delivery_method": "express",
        "delivery_days_min": 1,
        "delivery_days_max": 2,
        "delivery_fee": 35.00,
        "free_delivery_threshold": 250.00,
        "return_policy": "14 days return policy",
        "warranty_period": "N/A",
        "discount_percentage": 10,
        "tax_percentage": 14,
        "product_images": json.dumps([
            "https://example.com/omega3-1.jpg"
        ]),
        "specifications": json.dumps({
            "form": "Soft gelatin capsule",
            "color": "Golden",
            "package": "Bottle"
        }),
        "tags": "omega-3,heart-health,brain-health,fish-oil",
        "meta_title": "Omega-3 Fish Oil 1000mg | Medicum Egypt",
        "meta_description": "Premium Omega-3 fish oil supplements for heart and brain health.",
        "is_featured": True,
        "is_active": True,
        "weight_grams": 70,
        "dimensions_cm": "6x6x11"
    },
    {
        "product_code": "MED-009-CALC",
        "name_en": "Calcium 600mg + Vitamin D3",
        "name_ar": "كالسيوم 600 مجم + فيتامين د3",
        "description_en": "Calcium with Vitamin D3 for strong bones and teeth. Prevents osteoporosis.",
        "description_ar": "الكالسيوم مع فيتامين د3 لعظام وأسنان قوية. يمنع هشاشة العظام.",
        "category": "vitamins",
        "subcategory": "supplements",
        "brand": "Eva Pharma",
        "manufacturer": "Eva Pharma",
        "country_of_origin": "Egypt",
        "price_per_unit": 48.00,
        "currency": "EGP",
        "unit": "box",
        "unit_size": "30 tablets",
        "stock_quantity": 350,
        "min_order_quantity": 1,
        "max_order_quantity": 10,
        "sku": "CALC-600-30T",
        "barcode": "6221060002789",
        "hsn_code": "30045090",
        "requires_prescription": False,
        "is_controlled": False,
        "active_ingredient": "Calcium carbonate 600mg, Vitamin D3 400 IU",
        "dosage_form": "Chewable tablet",
        "side_effects": "Constipation, gas, bloating",
        "contraindications": "Hypercalcemia, kidney disease",
        "storage_conditions": "Store below 30°C",
        "expiry_date": "2027-02-28",
        "batch_number": "B2024-109",
        "seller_code": "PHARM-001",
        "seller_name": "El-Ezaby Pharmacy",
        "delivery_method": "standard",
        "delivery_days_min": 2,
        "delivery_days_max": 3,
        "delivery_fee": 30.00,
        "free_delivery_threshold": 200.00,
        "return_policy": "14 days return policy",
        "warranty_period": "N/A",
        "discount_percentage": 20,
        "tax_percentage": 14,
        "product_images": json.dumps([
            "https://example.com/calcium-1.jpg"
        ]),
        "specifications": json.dumps({
            "form": "Chewable tablet",
            "color": "White",
            "flavor": "Orange",
            "package": "Bottle"
        }),
        "tags": "calcium,vitamin-D,bone-health,osteoporosis",
        "meta_title": "Calcium 600mg + Vitamin D3 | Medicum Egypt",
        "meta_description": "Calcium and Vitamin D3 supplements for strong bones.",
        "is_featured": False,
        "is_active": True,
        "weight_grams": 80,
        "dimensions_cm": "7x7x12"
    },
    
    # Cold & Flu (10-12)
    {
        "product_code": "MED-010-CONG",
        "name_en": "Congestal Cold & Flu Tablets",
        "name_ar": "كونجستال أقراص للبرد والإنفلونزا",
        "description_en": "Multi-symptom cold and flu relief. Reduces fever, relieves congestion and body aches.",
        "description_ar": "علاج متعدد الأعراض للبرد والإنفلونزا. يخفض الحرارة ويخفف الاحتقان وآلام الجسم.",
        "category": "cold-flu",
        "subcategory": "oral-medications",
        "brand": "Sigma",
        "manufacturer": "Sigma Pharmaceuticals",
        "country_of_origin": "Egypt",
        "price_per_unit": 19.50,
        "currency": "EGP",
        "unit": "box",
        "unit_size": "20 tablets",
        "stock_quantity": 500,
        "min_order_quantity": 1,
        "max_order_quantity": 10,
        "sku": "CONG-20T",
        "barcode": "6221060003123",
        "hsn_code": "30049099",
        "requires_prescription": False,
        "is_controlled": False,
        "active_ingredient": "Paracetamol 650mg, Pseudoephedrine 60mg, Chlorpheniramine 4mg",
        "dosage_form": "Tablet",
        "side_effects": "Drowsiness, dry mouth, dizziness",
        "contraindications": "High blood pressure, glaucoma, MAO inhibitors",
        "storage_conditions": "Store below 25°C",
        "expiry_date": "2026-11-30",
        "batch_number": "B2024-110",
        "seller_code": "PHARM-003",
        "seller_name": "Roshdy Pharmacies",
        "delivery_method": "express",
        "delivery_days_min": 1,
        "delivery_days_max": 2,
        "delivery_fee": 35.00,
        "free_delivery_threshold": 150.00,
        "return_policy": "7 days return policy",
        "warranty_period": "N/A",
        "discount_percentage": 15,
        "tax_percentage": 14,
        "product_images": json.dumps([
            "https://example.com/congestal-1.jpg",
            "https://example.com/congestal-2.jpg"
        ]),
        "specifications": json.dumps({
            "form": "Tablet",
            "color": "White/Red",
            "package": "Blister pack"
        }),
        "tags": "cold,flu,fever,congestion,OTC",
        "meta_title": "Congestal Cold & Flu | Medicum Egypt",
        "meta_description": "Congestal tablets for cold and flu symptom relief.",
        "is_featured": True,
        "is_active": True,
        "weight_grams": 30,
        "dimensions_cm": "10x7x2"
    },
    {
        "product_code": "MED-011-FLUM",
        "name_en": "Flumeucil 600mg Effervescent",
        "name_ar": "فلوموسيل 600 مجم فوار",
        "description_en": "Mucolytic for chest congestion. Helps clear mucus from airways.",
        "description_ar": "مذيب للبلغم لاحتقان الصدر. يساعد على إزالة المخاط من الشعب الهوائية.",
        "category": "cold-flu",
        "subcategory": "oral-medications",
        "brand": "Zambon",
        "manufacturer": "Zambon Egypt",
        "country_of_origin": "Egypt",
        "price_per_unit": 65.00,
        "currency": "EGP",
        "unit": "box",
        "unit_size": "10 sachets",
        "stock_quantity": 200,
        "min_order_quantity": 1,
        "max_order_quantity": 5,
        "sku": "FLUM-600-10S",
        "barcode": "6221060003456",
        "hsn_code": "30049099",
        "requires_prescription": False,
        "is_controlled": False,
        "active_ingredient": "Acetylcysteine 600mg",
        "dosage_form": "Effervescent granules",
        "side_effects": "Nausea, vomiting, diarrhea",
        "contraindications": "Peptic ulcer, asthma",
        "storage_conditions": "Store below 25°C in dry place",
        "expiry_date": "2026-07-15",
        "batch_number": "B2024-111",
        "seller_code": "PHARM-002",
        "seller_name": "Seif Pharmacies",
        "delivery_method": "standard",
        "delivery_days_min": 2,
        "delivery_days_max": 3,
        "delivery_fee": 30.00,
        "free_delivery_threshold": 200.00,
        "return_policy": "7 days return policy",
        "warranty_period": "N/A",
        "discount_percentage": 5,
        "tax_percentage": 14,
        "product_images": json.dumps([
            "https://example.com/flumeucil-1.jpg"
        ]),
        "specifications": json.dumps({
            "form": "Effervescent granules",
            "color": "White",
            "flavor": "Orange",
            "package": "Sachets"
        }),
        "tags": "mucolytic,cough,chest-congestion,effervescent",
        "meta_title": "Flumeucil 600mg | Medicum Egypt",
        "meta_description": "Flumeucil effervescent for chest congestion relief.",
        "is_featured": False,
        "is_active": True,
        "weight_grams": 40,
        "dimensions_cm": "12x8x3"
    },
    {
        "product_code": "MED-012-OTRI",
        "name_en": "Otrivin Nasal Spray 0.1%",
        "name_ar": "أوتريفين بخاخ أنف 0.1%",
        "description_en": "Nasal decongestant spray for blocked nose. Fast relief from nasal congestion.",
        "description_ar": "بخاخ مزيل لاحتقان الأنف. راحة سريعة من احتقان الأنف.",
        "category": "cold-flu",
        "subcategory": "nasal-medications",
        "brand": "GSK",
        "manufacturer": "GlaxoSmithKline Egypt",
        "country_of_origin": "Egypt",
        "price_per_unit": 28.00,
        "currency": "EGP",
        "unit": "bottle",
        "unit_size": "10ml",
        "stock_quantity": 400,
        "min_order_quantity": 1,
        "max_order_quantity": 6,
        "sku": "OTRI-01-10ML",
        "barcode": "6221060003789",
        "hsn_code": "30049099",
        "requires_prescription": False,
        "is_controlled": False,
        "active_ingredient": "Xylometazoline HCl 0.1%",
        "dosage_form": "Nasal spray",
        "side_effects": "Burning sensation, dryness, rebound congestion with overuse",
        "contraindications": "Children under 12, narrow-angle glaucoma",
        "storage_conditions": "Store below 30°C",
        "expiry_date": "2026-04-30",
        "batch_number": "B2024-112",
        "seller_code": "PHARM-001",
        "seller_name": "El-Ezaby Pharmacy",
        "delivery_method": "express",
        "delivery_days_min": 1,
        "delivery_days_max": 2,
        "delivery_fee": 35.00,
        "free_delivery_threshold": 200.00,
        "return_policy": "No returns once opened",
        "warranty_period": "N/A",
        "discount_percentage": 10,
        "tax_percentage": 14,
        "product_images": json.dumps([
            "https://example.com/otrivin-1.jpg"
        ]),
        "specifications": json.dumps({
            "form": "Spray solution",
            "container": "Plastic bottle",
            "volume": "10ml"
        }),
        "tags": "nasal-spray,decongestant,blocked-nose,OTC",
        "meta_title": "Otrivin Nasal Spray | Medicum Egypt",
        "meta_description": "Otrivin nasal spray for fast relief from nasal congestion.",
        "is_featured": False,
        "is_active": True,
        "weight_grams": 25,
        "dimensions_cm": "3x3x10"
    },
    
    # Digestive Health (13-15)
    {
        "product_code": "MED-013-RANT",
        "name_en": "Rantidine 150mg Tablets",
        "name_ar": "رانتيدين 150 مجم أقراص",
        "description_en": "For heartburn and acid reflux. Reduces stomach acid production.",
        "description_ar": "لحرقة المعدة وارتجاع الحمض. يقلل من إنتاج حمض المعدة.",
        "category": "digestive",
        "subcategory": "oral-medications",
        "brand": "EIPICO",
        "manufacturer": "EIPICO Egypt",
        "country_of_origin": "Egypt",
        "price_per_unit": 22.00,
        "currency": "EGP",
        "unit": "box",
        "unit_size": "20 tablets",
        "stock_quantity": 350,
        "min_order_quantity": 1,
        "max_order_quantity": 8,
        "sku": "RANT-150-20T",
        "barcode": "6221060004123",
        "hsn_code": "30049099",
        "requires_prescription": False,
        "is_controlled": False,
        "active_ingredient": "Ranitidine HCl 150mg",
        "dosage_form": "Film-coated tablet",
        "side_effects": "Headache, dizziness, constipation",
        "contraindications": "Kidney disease, porphyria",
        "storage_conditions": "Store below 25°C",
        "expiry_date": "2026-08-31",
        "batch_number": "B2024-113",
        "seller_code": "PHARM-003",
        "seller_name": "Roshdy Pharmacies",
        "delivery_method": "standard",
        "delivery_days_min": 1,
        "delivery_days_max": 3,
        "delivery_fee": 30.00,
        "free_delivery_threshold": 200.00,
        "return_policy": "7 days return policy",
        "warranty_period": "N/A",
        "discount_percentage": 15,
        "tax_percentage": 14,
        "product_images": json.dumps([
            "https://example.com/rantidine-1.jpg"
        ]),
        "specifications": json.dumps({
            "form": "Film-coated tablet",
            "color": "White",
            "package": "Blister pack"
        }),
        "tags": "heartburn,acid-reflux,digestive,OTC",
        "meta_title": "Rantidine 150mg | Medicum Egypt",
        "meta_description": "Rantidine for heartburn and acid reflux relief.",
        "is_featured": False,
        "is_active": True,
        "weight_grams": 35,
        "dimensions_cm": "10x7x2"
    },
    {
        "product_code": "MED-014-LACT",
        "name_en": "Lactulose Syrup 667mg/ml",
        "name_ar": "لاكتيولوز شراب 667 مجم/مل",
        "description_en": "Gentle laxative for constipation relief. Safe for long-term use.",
        "description_ar": "ملين لطيف لعلاج الإمساك. آمن للاستخدام طويل الأمد.",
        "category": "digestive",
        "subcategory": "oral-medications",
        "brand": "Amriya",
        "manufacturer": "Amriya Pharmaceuticals",
        "country_of_origin": "Egypt",
        "price_per_unit": 18.00,
        "currency": "EGP",
        "unit": "bottle",
        "unit_size": "120ml",
        "stock_quantity": 250,
        "min_order_quantity": 1,
        "max_order_quantity": 6,
        "sku": "LACT-120ML",
        "barcode": "6221060004456",
        "hsn_code": "30049099",
        "requires_prescription": False,
        "is_controlled": False,
        "active_ingredient": "Lactulose 667mg/ml",
        "dosage_form": "Syrup",
        "side_effects": "Bloating, gas, cramping",
        "contraindications": "Galactosemia, intestinal obstruction",
        "storage_conditions": "Store below 25°C, do not freeze",
        "expiry_date": "2026-12-31",
        "batch_number": "B2024-114",
        "seller_code": "PHARM-002",
        "seller_name": "Seif Pharmacies",
        "delivery_method": "standard",
        "delivery_days_min": 2,
        "delivery_days_max": 3,
        "delivery_fee": 30.00,
        "free_delivery_threshold": 200.00,
        "return_policy": "No returns once opened",
        "warranty_period": "N/A",
        "discount_percentage": 10,
        "tax_percentage": 14,
        "product_images": json.dumps([
            "https://example.com/lactulose-1.jpg"
        ]),
        "specifications": json.dumps({
            "form": "Syrup",
            "color": "Clear",
            "volume": "120ml",
            "flavor": "Sweet"
        }),
        "tags": "laxative,constipation,digestive,OTC",
        "meta_title": "Lactulose Syrup | Medicum Egypt",
        "meta_description": "Lactulose syrup for gentle constipation relief.",
        "is_featured": False,
        "is_active": True,
        "weight_grams": 180,
        "dimensions_cm": "5x5x12"
    },
    {
        "product_code": "MED-015-ENTE",
        "name_en": "Enterogermina Probiotic",
        "name_ar": "إنتيروجيرمينا بروبيوتيك",
        "description_en": "Probiotic for digestive balance. Restores intestinal flora after antibiotics.",
        "description_ar": "بروبيوتيك لتوازن الجهاز الهضمي. يستعيد فلورا الأمعاء بعد المضادات الحيوية.",
        "category": "digestive",
        "subcategory": "probiotics",
        "brand": "Sanofi",
        "manufacturer": "Sanofi Egypt",
        "country_of_origin": "Egypt",
        "price_per_unit": 75.00,
        "currency": "EGP",
        "unit": "box",
        "unit_size": "10 vials",
        "stock_quantity": 150,
        "min_order_quantity": 1,
        "max_order_quantity": 5,
        "sku": "ENTE-10V",
        "barcode": "6221060004789",
        "hsn_code": "30049099",
        "requires_prescription": False,
        "is_controlled": False,
        "active_ingredient": "Bacillus clausii 2 billion spores",
        "dosage_form": "Oral suspension",
        "side_effects": "Very rare: skin rash",
        "contraindications": "Immunodeficiency",
        "storage_conditions": "Store below 30°C",
        "expiry_date": "2026-10-15",
        "batch_number": "B2024-115",
        "seller_code": "PHARM-001",
        "seller_name": "El-Ezaby Pharmacy",
        "delivery_method": "express",
        "delivery_days_min": 1,
        "delivery_days_max": 2,
        "delivery_fee": 35.00,
        "free_delivery_threshold": 250.00,
        "return_policy": "7 days return policy",
        "warranty_period": "N/A",
        "discount_percentage": 5,
        "tax_percentage": 14,
        "product_images": json.dumps([
            "https://example.com/enterogermina-1.jpg"
        ]),
        "specifications": json.dumps({
            "form": "Oral suspension",
            "container": "Vials",
            "volume": "5ml per vial"
        }),
        "tags": "probiotic,digestive-health,diarrhea,antibiotics",
        "meta_title": "Enterogermina Probiotic | Medicum Egypt",
        "meta_description": "Enterogermina probiotic for digestive health.",
        "is_featured": True,
        "is_active": True,
        "weight_grams": 80,
        "dimensions_cm": "10x8x4"
    },
    
    # Diabetes Care (16-17)
    {
        "product_code": "MED-016-GLUC",
        "name_en": "Glucophage 500mg Tablets",
        "name_ar": "جلوكوفاج 500 مجم أقراص",
        "description_en": "Metformin for type 2 diabetes. Controls blood sugar levels.",
        "description_ar": "ميتفورمين لمرض السكري من النوع 2. يتحكم في مستويات السكر في الدم.",
        "category": "diabetes",
        "subcategory": "oral-medications",
        "brand": "Merck",
        "manufacturer": "Merck Egypt",
        "country_of_origin": "Egypt",
        "price_per_unit": 38.00,
        "currency": "EGP",
        "unit": "box",
        "unit_size": "30 tablets",
        "stock_quantity": 200,
        "min_order_quantity": 1,
        "max_order_quantity": 5,
        "sku": "GLUC-500-30T",
        "barcode": "6221060005123",
        "hsn_code": "30049099",
        "requires_prescription": True,
        "is_controlled": False,
        "active_ingredient": "Metformin HCl 500mg",
        "dosage_form": "Film-coated tablet",
        "side_effects": "Nausea, diarrhea, stomach upset. Take with meals.",
        "contraindications": "Kidney disease, metabolic acidosis",
        "storage_conditions": "Store below 25°C",
        "expiry_date": "2026-09-30",
        "batch_number": "B2024-116",
        "seller_code": "PHARM-003",
        "seller_name": "Roshdy Pharmacies",
        "delivery_method": "standard",
        "delivery_days_min": 1,
        "delivery_days_max": 3,
        "delivery_fee": 30.00,
        "free_delivery_threshold": 200.00,
        "return_policy": "No returns for prescription medicines",
        "warranty_period": "N/A",
        "discount_percentage": 0,
        "tax_percentage": 14,
        "product_images": json.dumps([
            "https://example.com/glucophage-1.jpg"
        ]),
        "specifications": json.dumps({
            "form": "Film-coated tablet",
            "color": "White",
            "package": "Blister pack"
        }),
        "tags": "diabetes,metformin,blood-sugar,prescription",
        "meta_title": "Glucophage 500mg | Medicum Egypt",
        "meta_description": "Glucophage metformin for type 2 diabetes. Prescription required.",
        "is_featured": False,
        "is_active": True,
        "weight_grams": 45,
        "dimensions_cm": "10x7x3"
    },
    {
        "product_code": "MED-017-TEST",
        "name_en": "Blood Glucose Test Strips",
        "name_ar": "شرائط اختبار جلوكوز الدم",
        "description_en": "Accurate blood glucose test strips. Compatible with most glucometers.",
        "description_ar": "شرائط دقيقة لاختبار جلوكوز الدم. متوافقة مع معظم أجهزة قياس السكر.",
        "category": "diabetes",
        "subcategory": "testing-supplies",
        "brand": "Accu-Chek",
        "manufacturer": "Roche Egypt",
        "country_of_origin": "Egypt",
        "price_per_unit": 120.00,
        "currency": "EGP",
        "unit": "box",
        "unit_size": "50 strips",
        "stock_quantity": 300,
        "min_order_quantity": 1,
        "max_order_quantity": 10,
        "sku": "TEST-GLU-50",
        "barcode": "6221060005456",
        "hsn_code": "38220090",
        "requires_prescription": False,
        "is_controlled": False,
        "active_ingredient": "N/A",
        "dosage_form": "Test strip",
        "side_effects": "N/A",
        "contraindications": "N/A",
        "storage_conditions": "Store in cool, dry place. Keep container closed.",
        "expiry_date": "2025-12-31",
        "batch_number": "B2024-117",
        "seller_code": "PHARM-002",
        "seller_name": "Seif Pharmacies",
        "delivery_method": "express",
        "delivery_days_min": 1,
        "delivery_days_max": 2,
        "delivery_fee": 35.00,
        "free_delivery_threshold": 300.00,
        "return_policy": "Unopened only within 7 days",
        "warranty_period": "N/A",
        "discount_percentage": 10,
        "tax_percentage": 14,
        "product_images": json.dumps([
            "https://example.com/test-strips-1.jpg"
        ]),
        "specifications": json.dumps({
            "quantity": "50 strips",
            "compatibility": "Most glucometers",
            "sample_size": "0.6 µL"
        }),
        "tags": "diabetes,blood-glucose,test-strips,monitoring",
        "meta_title": "Blood Glucose Test Strips | Medicum Egypt",
        "meta_description": "Accurate blood glucose test strips for diabetes monitoring.",
        "is_featured": True,
        "is_active": True,
        "weight_grams": 60,
        "dimensions_cm": "8x6x5"
    },
    
    # Personal Care (18-20)
    {
        "product_code": "MED-018-PANT",
        "name_en": "Pantene Pro-V Shampoo 400ml",
        "name_ar": "شامبو بانتين برو-في 400 مل",
        "description_en": "Nourishing shampoo for healthy, shiny hair. With Pro-Vitamin formula.",
        "description_ar": "شامبو مغذي لشعر صحي ولامع. بتركيبة البرو-فيتامين.",
        "category": "personal-care",
        "subcategory": "hair-care",
        "brand": "Pantene",
        "manufacturer": "P&G Egypt",
        "country_of_origin": "Egypt",
        "price_per_unit": 65.00,
        "currency": "EGP",
        "unit": "bottle",
        "unit_size": "400ml",
        "stock_quantity": 200,
        "min_order_quantity": 1,
        "max_order_quantity": 6,
        "sku": "PANT-SHA-400",
        "barcode": "6221060005789",
        "hsn_code": "33051000",
        "requires_prescription": False,
        "is_controlled": False,
        "active_ingredient": "Pro-Vitamin B5, Silk Protein",
        "dosage_form": "Shampoo",
        "side_effects": "Rare: scalp irritation in sensitive individuals",
        "contraindications": "Allergy to ingredients",
        "storage_conditions": "Store at room temperature",
        "expiry_date": "2027-06-30",
        "batch_number": "B2024-118",
        "seller_code": "PHARM-001",
        "seller_name": "El-Ezaby Pharmacy",
        "delivery_method": "standard",
        "delivery_days_min": 2,
        "delivery_days_max": 3,
        "delivery_fee": 30.00,
        "free_delivery_threshold": 200.00,
        "return_policy": "14 days unopened",
        "warranty_period": "N/A",
        "discount_percentage": 20,
        "tax_percentage": 14,
        "product_images": json.dumps([
            "https://example.com/pantene-1.jpg"
        ]),
        "specifications": json.dumps({
            "volume": "400ml",
            "hair_type": "All hair types",
            "scent": "Fresh"
        }),
        "tags": "shampoo,hair-care,pantene,personal-care",
        "meta_title": "Pantene Pro-V Shampoo | Medicum Egypt",
        "meta_description": "Pantene Pro-V nourishing shampoo for healthy hair.",
        "is_featured": False,
        "is_active": True,
        "weight_grams": 450,
        "dimensions_cm": "6x6x20"
    },
    {
        "product_code": "MED-019-SENS",
        "name_en": "Sensodyne Toothpaste 75ml",
        "name_ar": "معجون أسنان سنسوداين 75 مل",
        "description_en": "Toothpaste for sensitive teeth. Provides 24/7 protection.",
        "description_ar": "معجون أسنان للأسنان الحساسة. يوفر حماية على مدار الساعة.",
        "category": "personal-care",
        "subcategory": "oral-care",
        "brand": "Sensodyne",
        "manufacturer": "GSK Egypt",
        "country_of_origin": "Egypt",
        "price_per_unit": 45.00,
        "currency": "EGP",
        "unit": "tube",
        "unit_size": "75ml",
        "stock_quantity": 350,
        "min_order_quantity": 1,
        "max_order_quantity": 8,
        "sku": "SENS-75ML",
        "barcode": "6221060006123",
        "hsn_code": "33061000",
        "requires_prescription": False,
        "is_controlled": False,
        "active_ingredient": "Potassium Nitrate 5%, Sodium Fluoride 0.254%",
        "dosage_form": "Toothpaste",
        "side_effects": "N/A",
        "contraindications": "Children under 12 without supervision",
        "storage_conditions": "Store below 30°C",
        "expiry_date": "2027-03-31",
        "batch_number": "B2024-119",
        "seller_code": "PHARM-003",
        "seller_name": "Roshdy Pharmacies",
        "delivery_method": "standard",
        "delivery_days_min": 1,
        "delivery_days_max": 3,
        "delivery_fee": 30.00,
        "free_delivery_threshold": 200.00,
        "return_policy": "14 days unopened",
        "warranty_period": "N/A",
        "discount_percentage": 15,
        "tax_percentage": 14,
        "product_images": json.dumps([
            "https://example.com/sensodyne-1.jpg"
        ]),
        "specifications": json.dumps({
            "volume": "75ml",
            "flavor": "Fresh Mint",
            "protection": "24/7 sensitivity protection"
        }),
        "tags": "toothpaste,sensitive-teeth,oral-care,sensodyne",
        "meta_title": "Sensodyne Toothpaste | Medicum Egypt",
        "meta_description": "Sensodyne toothpaste for sensitive teeth protection.",
        "is_featured": False,
        "is_active": True,
        "weight_grams": 100,
        "dimensions_cm": "4x4x15"
    },
    {
        "product_code": "MED-020-DETT",
        "name_en": "Dettol Antiseptic Liquid 500ml",
        "name_ar": "سائل ديتول المطهر 500 مل",
        "description_en": "Multi-purpose antiseptic for wound cleaning and household disinfection.",
        "description_ar": "مطهر متعدد الأغراض لتنظيف الجروح وتطهير المنزل.",
        "category": "personal-care",
        "subcategory": "antiseptics",
        "brand": "Dettol",
        "manufacturer": "Reckitt Egypt",
        "country_of_origin": "Egypt",
        "price_per_unit": 58.00,
        "currency": "EGP",
        "unit": "bottle",
        "unit_size": "500ml",
        "stock_quantity": 400,
        "min_order_quantity": 1,
        "max_order_quantity": 10,
        "sku": "DETT-500ML",
        "barcode": "6221060006456",
        "hsn_code": "38089400",
        "requires_prescription": False,
        "is_controlled": False,
        "active_ingredient": "Chloroxylenol 4.8%",
        "dosage_form": "Liquid",
        "side_effects": "Skin irritation if undiluted",
        "contraindications": "Do not use undiluted on skin",
        "storage_conditions": "Store below 30°C, keep away from children",
        "expiry_date": "2027-12-31",
        "batch_number": "B2024-120",
        "seller_code": "PHARM-002",
        "seller_name": "Seif Pharmacies",
        "delivery_method": "express",
        "delivery_days_min": 1,
        "delivery_days_max": 2,
        "delivery_fee": 35.00,
        "free_delivery_threshold": 250.00,
        "return_policy": "14 days unopened",
        "warranty_period": "N/A",
        "discount_percentage": 10,
        "tax_percentage": 14,
        "product_images": json.dumps([
            "https://example.com/dettol-1.jpg",
            "https://example.com/dettol-2.jpg"
        ]),
        "specifications": json.dumps({
            "volume": "500ml",
            "concentration": "4.8% Chloroxylenol",
            "uses": "Wounds, household cleaning"
        }),
        "tags": "antiseptic,disinfectant,dettol,first-aid",
        "meta_title": "Dettol Antiseptic Liquid | Medicum Egypt",
        "meta_description": "Dettol antiseptic liquid for wound care and disinfection.",
        "is_featured": True,
        "is_active": True,
        "weight_grams": 550,
        "dimensions_cm": "7x7x20"
    }
]

def create_excel_file():
    """Create Excel file with product data"""
    
    # Convert to DataFrame
    df = pd.DataFrame(products_data)
    
    # Create Excel writer
    output_file = '/home/user/webapp/medicum_products_poc.xlsx'
    
    with pd.ExcelWriter(output_file, engine='openpyxl') as writer:
        # Write main data
        df.to_excel(writer, sheet_name='Products', index=False)
        
        # Get workbook and worksheet
        workbook = writer.book
        worksheet = writer.sheets['Products']
        
        # Apply styles
        header_font = Font(bold=True, color="FFFFFF")
        header_fill = PatternFill(start_color="1F4E79", end_color="1F4E79", fill_type="solid")
        header_alignment = Alignment(horizontal="center", vertical="center")
        
        # Style headers
        for cell in worksheet[1]:
            cell.font = header_font
            cell.fill = header_fill
            cell.alignment = header_alignment
        
        # Auto-adjust column widths
        for column in worksheet.columns:
            max_length = 0
            column_letter = column[0].column_letter
            
            for cell in column:
                try:
                    if cell.value:
                        max_length = max(max_length, len(str(cell.value)))
                except:
                    pass
            
            adjusted_width = min(max_length + 2, 50)
            worksheet.column_dimensions[column_letter].width = adjusted_width
        
        # Add instructions sheet
        instructions_df = pd.DataFrame({
            'Field': ['product_code', 'name_en', 'name_ar', 'price_per_unit', 'requires_prescription'],
            'Description': [
                'Unique product identifier',
                'Product name in English',
                'Product name in Arabic',
                'Price in Egyptian Pounds',
                'TRUE if prescription required, FALSE otherwise'
            ],
            'Required': ['Yes', 'Yes', 'Yes', 'Yes', 'Yes'],
            'Example': ['MED-001-BRUF', 'Brufen 400mg', 'بروفين 400 مجم', '32.50', 'FALSE']
        })
        
        instructions_df.to_excel(writer, sheet_name='Instructions', index=False)
        
        # Style instructions sheet
        inst_worksheet = writer.sheets['Instructions']
        for cell in inst_worksheet[1]:
            cell.font = header_font
            cell.fill = header_fill
            cell.alignment = header_alignment
        
        # Auto-adjust columns
        for column in inst_worksheet.columns:
            max_length = 0
            column_letter = column[0].column_letter
            for cell in column:
                try:
                    if cell.value:
                        max_length = max(max_length, len(str(cell.value)))
                except:
                    pass
            adjusted_width = min(max_length + 2, 50)
            inst_worksheet.column_dimensions[column_letter].width = adjusted_width
    
    print(f"✅ Excel file created: {output_file}")
    print(f"📊 Total products: {len(products_data)}")
    return output_file

if __name__ == "__main__":
    create_excel_file()