#!/usr/bin/env node

/**
 * Load products data directly to Supabase using REST API
 */

const SUPABASE_URL = 'https://qxgmnbbbospkemikpjrv.supabase.co';
const SUPABASE_SERVICE_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF4Z21uYmJib3Nwa2VtaWtwanJ2Iiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc1ODg3OTA2NCwiZXhwIjoyMDc0NDU1MDY0fQ.6JfZwPkEfB51DAMh9-ecr9ZfJmdFhwGNjMZiy2u_Jik';

// First, let's create the tables using individual REST API calls
async function createTables() {
  console.log('📊 Creating database tables...');
  
  // Create categories table first (no dependencies)
  const categories = [
    { name_en: 'Pain Relief', name_ar: 'مسكنات الألم', slug: 'pain-relief' },
    { name_en: 'Antibiotics', name_ar: 'المضادات الحيوية', slug: 'antibiotics' },
    { name_en: 'Vitamins', name_ar: 'الفيتامينات', slug: 'vitamins' },
    { name_en: 'Cold & Flu', name_ar: 'البرد والأنفلونزا', slug: 'cold-flu' },
    { name_en: 'Digestive', name_ar: 'الجهاز الهضمي', slug: 'digestive' },
    { name_en: 'Diabetes', name_ar: 'السكري', slug: 'diabetes' },
    { name_en: 'Personal Care', name_ar: 'العناية الشخصية', slug: 'personal-care' }
  ];

  try {
    const catResponse = await fetch(`${SUPABASE_URL}/rest/v1/categories`, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'apikey': SUPABASE_SERVICE_KEY,
        'Authorization': `Bearer ${SUPABASE_SERVICE_KEY}`,
        'Prefer': 'return=minimal'
      },
      body: JSON.stringify(categories)
    });
    
    if (catResponse.ok) {
      console.log('✅ Categories table created/populated');
    } else {
      console.log('⚠️ Categories table might not exist yet');
    }
  } catch (error) {
    console.log('⚠️ Could not create categories:', error.message);
  }
}

async function loadProducts() {
  console.log('📦 Loading products into Supabase...');
  
  // Products data
  const products = [
    // Pain Relief Products (1-3)
    {
      product_code: 'MED-001-BRUF',
      sku: 'BRUF-400-30T',
      barcode: '6221060000123',
      name_en: 'Brufen 400mg Tablets',
      name_ar: 'بروفين 400 مجم أقراص',
      description_en: 'Anti-inflammatory pain relief tablets. Effective for arthritis, dental pain, and fever reduction.',
      description_ar: 'أقراص مضادة للالتهابات لتخفيف الألم. فعال لالتهاب المفاصل وآلام الأسنان وخفض الحرارة.',
      category: 'pain-relief',
      subcategory: 'oral-medications',
      brand: 'Abbott',
      manufacturer: 'Abbott Egypt',
      country_of_origin: 'Egypt',
      price: 32.50,
      price_per_unit: 32.50,
      discount_percentage: 5,
      tax_percentage: 14,
      stock_quantity: 450,
      min_order_quantity: 1,
      max_order_quantity: 10,
      requires_prescription: false,
      active_ingredient: 'Ibuprofen 400mg',
      dosage_form: 'Tablet',
      side_effects: 'May cause stomach upset, heartburn. Take with food.',
      contraindications: 'Stomach ulcers, severe kidney or liver disease',
      storage_conditions: 'Store below 25°C in a dry place',
      delivery_method: 'express',
      delivery_days_min: 1,
      delivery_days_max: 2,
      delivery_fee: 35.00,
      image_url: 'https://via.placeholder.com/400x300/FF6B6B/FFFFFF?text=Brufen+400mg',
      product_images: ['https://via.placeholder.com/400x300/FF6B6B/FFFFFF?text=Brufen+400mg'],
      unit: 'box',
      unit_size: '30 tablets',
      unit_item: 'box',
      is_featured: true,
      is_active: true,
      in_stock: true,
      meta_title: 'Buy Brufen 400mg Online | Medicum Egypt',
      meta_description: 'Brufen 400mg anti-inflammatory tablets for pain relief.',
      tags: ['pain-relief', 'anti-inflammatory', 'arthritis', 'fever']
    },
    {
      product_code: 'MED-002-PAND',
      sku: 'PAND-EXT-24T',
      barcode: '6221060000456',
      name_en: 'Panadol Extra Tablets',
      name_ar: 'بانادول إكسترا أقراص',
      description_en: 'Advanced pain relief with paracetamol and caffeine. For headaches and strong pain.',
      description_ar: 'تسكين متقدم للألم مع الباراسيتامول والكافيين. للصداع والألم الشديد.',
      category: 'pain-relief',
      subcategory: 'oral-medications',
      brand: 'GSK',
      manufacturer: 'GlaxoSmithKline Egypt',
      country_of_origin: 'Egypt',
      price: 28.00,
      price_per_unit: 28.00,
      discount_percentage: 10,
      tax_percentage: 14,
      stock_quantity: 600,
      min_order_quantity: 1,
      max_order_quantity: 15,
      requires_prescription: false,
      active_ingredient: 'Paracetamol 500mg, Caffeine 65mg',
      dosage_form: 'Tablet',
      side_effects: 'Rare: nausea, insomnia due to caffeine',
      contraindications: 'Severe liver disease, caffeine sensitivity',
      storage_conditions: 'Store below 30°C',
      delivery_method: 'standard',
      delivery_days_min: 2,
      delivery_days_max: 3,
      delivery_fee: 30.00,
      image_url: 'https://via.placeholder.com/400x300/4ECDC4/FFFFFF?text=Panadol+Extra',
      product_images: ['https://via.placeholder.com/400x300/4ECDC4/FFFFFF?text=Panadol+Extra'],
      unit: 'box',
      unit_size: '24 tablets',
      unit_item: 'box',
      is_featured: true,
      is_active: true,
      in_stock: true,
      meta_title: 'Buy Panadol Extra Online | Medicum Egypt',
      meta_description: 'Panadol Extra for advanced pain relief.',
      tags: ['pain-relief', 'headache', 'paracetamol', 'OTC']
    },
    {
      product_code: 'MED-003-VOLT',
      sku: 'VOLT-50-20T',
      barcode: '6221060000789',
      name_en: 'Voltaren 50mg Tablets',
      name_ar: 'فولتارين 50 مجم أقراص',
      description_en: 'Diclofenac sodium for inflammation and pain. Effective for back pain and joint disorders.',
      description_ar: 'ديكلوفيناك الصوديوم للالتهاب والألم. فعال لآلام الظهر واضطرابات المفاصل.',
      category: 'pain-relief',
      subcategory: 'oral-medications',
      brand: 'Novartis',
      manufacturer: 'Novartis Egypt',
      country_of_origin: 'Egypt',
      price: 45.00,
      price_per_unit: 45.00,
      discount_percentage: 0,
      tax_percentage: 14,
      stock_quantity: 350,
      min_order_quantity: 1,
      max_order_quantity: 8,
      requires_prescription: true,
      active_ingredient: 'Diclofenac sodium 50mg',
      dosage_form: 'Enteric-coated tablet',
      side_effects: 'May cause stomach upset, dizziness. Take with food.',
      contraindications: 'Stomach ulcers, heart disease, pregnancy (3rd trimester)',
      storage_conditions: 'Store below 25°C',
      delivery_method: 'express',
      delivery_days_min: 1,
      delivery_days_max: 2,
      delivery_fee: 35.00,
      image_url: 'https://via.placeholder.com/400x300/95E1D3/333333?text=Voltaren+50mg',
      product_images: ['https://via.placeholder.com/400x300/95E1D3/333333?text=Voltaren+50mg'],
      unit: 'box',
      unit_size: '20 tablets',
      unit_item: 'box',
      is_featured: false,
      is_active: true,
      in_stock: true,
      meta_title: 'Voltaren 50mg Tablets | Medicum Egypt',
      meta_description: 'Voltaren 50mg for inflammation and severe pain.',
      tags: ['anti-inflammatory', 'arthritis', 'back-pain', 'prescription']
    },
    // Antibiotics (4-6)
    {
      product_code: 'MED-004-AUGM',
      sku: 'AUGM-1G-14T',
      barcode: '6221060001234',
      name_en: 'Augmentin 1g Tablets',
      name_ar: 'أوجمنتين 1 جم أقراص',
      description_en: 'Powerful antibiotic combination for bacterial infections.',
      description_ar: 'مزيج قوي من المضادات الحيوية للعدوى البكتيرية.',
      category: 'antibiotics',
      subcategory: 'oral-medications',
      brand: 'GSK',
      manufacturer: 'GlaxoSmithKline Egypt',
      country_of_origin: 'Egypt',
      price: 89.50,
      price_per_unit: 89.50,
      discount_percentage: 0,
      tax_percentage: 14,
      stock_quantity: 200,
      min_order_quantity: 1,
      max_order_quantity: 3,
      requires_prescription: true,
      active_ingredient: 'Amoxicillin 875mg, Clavulanic acid 125mg',
      dosage_form: 'Film-coated tablet',
      side_effects: 'Diarrhea, nausea, skin rash. Take with food.',
      contraindications: 'Penicillin allergy, liver problems',
      storage_conditions: 'Store below 25°C in dry place',
      delivery_method: 'standard',
      delivery_days_min: 1,
      delivery_days_max: 3,
      delivery_fee: 30.00,
      image_url: 'https://via.placeholder.com/400x300/F38181/FFFFFF?text=Augmentin+1g',
      product_images: ['https://via.placeholder.com/400x300/F38181/FFFFFF?text=Augmentin+1g'],
      unit: 'box',
      unit_size: '14 tablets',
      unit_item: 'box',
      is_featured: false,
      is_active: true,
      in_stock: true,
      meta_title: 'Augmentin 1g Antibiotic | Medicum Egypt',
      meta_description: 'Augmentin 1g powerful antibiotic.',
      tags: ['antibiotic', 'bacterial-infection', 'prescription']
    },
    {
      product_code: 'MED-005-ZITH',
      sku: 'ZITH-500-3T',
      barcode: '6221060001567',
      name_en: 'Zithromax 500mg Tablets',
      name_ar: 'زيثروماكس 500 مجم أقراص',
      description_en: 'Azithromycin antibiotic for respiratory infections.',
      description_ar: 'أزيثروميسين مضاد حيوي لالتهابات الجهاز التنفسي.',
      category: 'antibiotics',
      subcategory: 'oral-medications',
      brand: 'Pfizer',
      manufacturer: 'Pfizer Egypt',
      country_of_origin: 'Egypt',
      price: 95.00,
      price_per_unit: 95.00,
      discount_percentage: 0,
      tax_percentage: 14,
      stock_quantity: 150,
      min_order_quantity: 1,
      max_order_quantity: 2,
      requires_prescription: true,
      active_ingredient: 'Azithromycin 500mg',
      dosage_form: 'Film-coated tablet',
      side_effects: 'Stomach upset, diarrhea, headache',
      contraindications: 'Liver disease, heart rhythm problems',
      storage_conditions: 'Store below 30°C',
      delivery_method: 'express',
      delivery_days_min: 1,
      delivery_days_max: 2,
      delivery_fee: 35.00,
      image_url: 'https://via.placeholder.com/400x300/AA96DA/FFFFFF?text=Zithromax+500mg',
      product_images: ['https://via.placeholder.com/400x300/AA96DA/FFFFFF?text=Zithromax+500mg'],
      unit: 'box',
      unit_size: '3 tablets',
      unit_item: 'box',
      is_featured: false,
      is_active: true,
      in_stock: true,
      meta_title: 'Zithromax 500mg | Medicum Egypt',
      meta_description: 'Zithromax azithromycin antibiotic.',
      tags: ['antibiotic', 'azithromycin', 'respiratory', 'prescription']
    },
    {
      product_code: 'MED-006-CIPR',
      sku: 'CIPR-500-10T',
      barcode: '6221060001890',
      name_en: 'Ciprofar 500mg Tablets',
      name_ar: 'سيبروفار 500 مجم أقراص',
      description_en: 'Ciprofloxacin for urinary tract and respiratory infections.',
      description_ar: 'سيبروفلوكساسين لالتهابات المسالك البولية والجهاز التنفسي.',
      category: 'antibiotics',
      subcategory: 'oral-medications',
      brand: 'Pharco',
      manufacturer: 'Pharco Pharmaceuticals',
      country_of_origin: 'Egypt',
      price: 42.00,
      price_per_unit: 42.00,
      discount_percentage: 5,
      tax_percentage: 14,
      stock_quantity: 300,
      min_order_quantity: 1,
      max_order_quantity: 5,
      requires_prescription: true,
      active_ingredient: 'Ciprofloxacin 500mg',
      dosage_form: 'Film-coated tablet',
      side_effects: 'Nausea, diarrhea, dizziness. Avoid sun exposure.',
      contraindications: 'Pregnancy, children under 18, tendon problems',
      storage_conditions: 'Store below 25°C',
      delivery_method: 'standard',
      delivery_days_min: 2,
      delivery_days_max: 3,
      delivery_fee: 30.00,
      image_url: 'https://via.placeholder.com/400x300/FCBAD3/333333?text=Ciprofar+500mg',
      product_images: ['https://via.placeholder.com/400x300/FCBAD3/333333?text=Ciprofar+500mg'],
      unit: 'box',
      unit_size: '10 tablets',
      unit_item: 'box',
      is_featured: false,
      is_active: true,
      in_stock: true,
      meta_title: 'Ciprofar 500mg Antibiotic | Medicum Egypt',
      meta_description: 'Ciprofloxacin 500mg for bacterial infections.',
      tags: ['antibiotic', 'UTI', 'ciprofloxacin', 'prescription']
    },
    // Vitamins & Supplements (7-9)
    {
      product_code: 'MED-007-VITD',
      sku: 'VITD-5000-30C',
      barcode: '6221060002123',
      name_en: 'Vitamin D3 5000 IU Capsules',
      name_ar: 'فيتامين د3 5000 وحدة دولية كبسولات',
      description_en: 'High strength Vitamin D3 for bone health and immunity.',
      description_ar: 'فيتامين د3 عالي القوة لصحة العظام والمناعة.',
      category: 'vitamins',
      subcategory: 'supplements',
      brand: 'Mepaco',
      manufacturer: 'Mepaco Egypt',
      country_of_origin: 'Egypt',
      price: 55.00,
      price_per_unit: 55.00,
      discount_percentage: 15,
      tax_percentage: 14,
      stock_quantity: 400,
      min_order_quantity: 1,
      max_order_quantity: 10,
      requires_prescription: false,
      active_ingredient: 'Cholecalciferol 5000 IU',
      dosage_form: 'Soft gelatin capsule',
      side_effects: 'Rare: hypercalcemia with excessive doses',
      contraindications: 'Hypercalcemia, kidney stones',
      storage_conditions: 'Store below 25°C, protect from light',
      delivery_method: 'standard',
      delivery_days_min: 1,
      delivery_days_max: 3,
      delivery_fee: 30.00,
      image_url: 'https://via.placeholder.com/400x300/FFFFD2/333333?text=Vitamin+D3',
      product_images: ['https://via.placeholder.com/400x300/FFFFD2/333333?text=Vitamin+D3'],
      unit: 'box',
      unit_size: '30 capsules',
      unit_item: 'box',
      is_featured: true,
      is_active: true,
      in_stock: true,
      meta_title: 'Vitamin D3 5000 IU | Medicum Egypt',
      meta_description: 'High strength Vitamin D3 supplements.',
      tags: ['vitamin-D', 'bone-health', 'immunity', 'supplement']
    },
    {
      product_code: 'MED-008-OMEG',
      sku: 'OMEG-1000-30C',
      barcode: '6221060002456',
      name_en: 'Omega-3 Fish Oil 1000mg',
      name_ar: 'أوميغا 3 زيت السمك 1000 مجم',
      description_en: 'Premium omega-3 fatty acids for heart and brain health.',
      description_ar: 'أحماض أوميغا 3 الدهنية الممتازة لصحة القلب والدماغ.',
      category: 'vitamins',
      subcategory: 'supplements',
      brand: 'Sedico',
      manufacturer: 'Sedico Pharmaceuticals',
      country_of_origin: 'Egypt',
      price: 85.00,
      price_per_unit: 85.00,
      discount_percentage: 10,
      tax_percentage: 14,
      stock_quantity: 250,
      min_order_quantity: 1,
      max_order_quantity: 8,
      requires_prescription: false,
      active_ingredient: 'Fish Oil 1000mg (EPA 180mg, DHA 120mg)',
      dosage_form: 'Soft gelatin capsule',
      side_effects: 'Fishy aftertaste, mild stomach upset',
      contraindications: 'Fish allergy, bleeding disorders',
      storage_conditions: 'Store below 25°C, refrigerate after opening',
      delivery_method: 'express',
      delivery_days_min: 1,
      delivery_days_max: 2,
      delivery_fee: 35.00,
      image_url: 'https://via.placeholder.com/400x300/A8E6CF/333333?text=Omega-3',
      product_images: ['https://via.placeholder.com/400x300/A8E6CF/333333?text=Omega-3'],
      unit: 'box',
      unit_size: '30 capsules',
      unit_item: 'box',
      is_featured: true,
      is_active: true,
      in_stock: true,
      meta_title: 'Omega-3 Fish Oil 1000mg | Medicum Egypt',
      meta_description: 'Premium Omega-3 fish oil supplements.',
      tags: ['omega-3', 'heart-health', 'brain-health', 'fish-oil']
    },
    {
      product_code: 'MED-009-CALC',
      sku: 'CALC-600-30T',
      barcode: '6221060002789',
      name_en: 'Calcium 600mg + Vitamin D3',
      name_ar: 'كالسيوم 600 مجم + فيتامين د3',
      description_en: 'Calcium with Vitamin D3 for strong bones and teeth.',
      description_ar: 'الكالسيوم مع فيتامين د3 لعظام وأسنان قوية.',
      category: 'vitamins',
      subcategory: 'supplements',
      brand: 'Eva Pharma',
      manufacturer: 'Eva Pharma',
      country_of_origin: 'Egypt',
      price: 48.00,
      price_per_unit: 48.00,
      discount_percentage: 20,
      tax_percentage: 14,
      stock_quantity: 350,
      min_order_quantity: 1,
      max_order_quantity: 10,
      requires_prescription: false,
      active_ingredient: 'Calcium carbonate 600mg, Vitamin D3 400 IU',
      dosage_form: 'Chewable tablet',
      side_effects: 'Constipation, gas, bloating',
      contraindications: 'Hypercalcemia, kidney disease',
      storage_conditions: 'Store below 30°C',
      delivery_method: 'standard',
      delivery_days_min: 2,
      delivery_days_max: 3,
      delivery_fee: 30.00,
      image_url: 'https://via.placeholder.com/400x300/FFD3B6/333333?text=Calcium+D3',
      product_images: ['https://via.placeholder.com/400x300/FFD3B6/333333?text=Calcium+D3'],
      unit: 'box',
      unit_size: '30 tablets',
      unit_item: 'box',
      is_featured: false,
      is_active: true,
      in_stock: true,
      meta_title: 'Calcium 600mg + Vitamin D3 | Medicum Egypt',
      meta_description: 'Calcium and Vitamin D3 supplements.',
      tags: ['calcium', 'vitamin-D', 'bone-health', 'osteoporosis']
    },
    // Cold & Flu (10-12)
    {
      product_code: 'MED-010-CONG',
      sku: 'CONG-20T',
      barcode: '6221060003123',
      name_en: 'Congestal Cold & Flu Tablets',
      name_ar: 'كونجستال أقراص للبرد والإنفلونزا',
      description_en: 'Multi-symptom cold and flu relief.',
      description_ar: 'علاج متعدد الأعراض للبرد والإنفلونزا.',
      category: 'cold-flu',
      subcategory: 'oral-medications',
      brand: 'Sigma',
      manufacturer: 'Sigma Pharmaceuticals',
      country_of_origin: 'Egypt',
      price: 19.50,
      price_per_unit: 19.50,
      discount_percentage: 15,
      tax_percentage: 14,
      stock_quantity: 500,
      min_order_quantity: 1,
      max_order_quantity: 10,
      requires_prescription: false,
      active_ingredient: 'Paracetamol 650mg, Pseudoephedrine 60mg, Chlorpheniramine 4mg',
      dosage_form: 'Tablet',
      side_effects: 'Drowsiness, dry mouth, dizziness',
      contraindications: 'High blood pressure, glaucoma, MAO inhibitors',
      storage_conditions: 'Store below 25°C',
      delivery_method: 'express',
      delivery_days_min: 1,
      delivery_days_max: 2,
      delivery_fee: 35.00,
      image_url: 'https://via.placeholder.com/400x300/FFAAA5/FFFFFF?text=Congestal',
      product_images: ['https://via.placeholder.com/400x300/FFAAA5/FFFFFF?text=Congestal'],
      unit: 'box',
      unit_size: '20 tablets',
      unit_item: 'box',
      is_featured: true,
      is_active: true,
      in_stock: true,
      meta_title: 'Congestal Cold & Flu | Medicum Egypt',
      meta_description: 'Congestal tablets for cold and flu relief.',
      tags: ['cold', 'flu', 'fever', 'congestion', 'OTC']
    },
    {
      product_code: 'MED-011-FLUM',
      sku: 'FLUM-600-10S',
      barcode: '6221060003456',
      name_en: 'Flumeucil 600mg Effervescent',
      name_ar: 'فلوموسيل 600 مجم فوار',
      description_en: 'Mucolytic for chest congestion.',
      description_ar: 'مذيب للبلغم لاحتقان الصدر.',
      category: 'cold-flu',
      subcategory: 'oral-medications',
      brand: 'Zambon',
      manufacturer: 'Zambon Egypt',
      country_of_origin: 'Egypt',
      price: 65.00,
      price_per_unit: 65.00,
      discount_percentage: 5,
      tax_percentage: 14,
      stock_quantity: 200,
      min_order_quantity: 1,
      max_order_quantity: 5,
      requires_prescription: false,
      active_ingredient: 'Acetylcysteine 600mg',
      dosage_form: 'Effervescent granules',
      side_effects: 'Nausea, vomiting, diarrhea',
      contraindications: 'Peptic ulcer, asthma',
      storage_conditions: 'Store below 25°C in dry place',
      delivery_method: 'standard',
      delivery_days_min: 2,
      delivery_days_max: 3,
      delivery_fee: 30.00,
      image_url: 'https://via.placeholder.com/400x300/FF8B94/FFFFFF?text=Flumeucil',
      product_images: ['https://via.placeholder.com/400x300/FF8B94/FFFFFF?text=Flumeucil'],
      unit: 'box',
      unit_size: '10 sachets',
      unit_item: 'box',
      is_featured: false,
      is_active: true,
      in_stock: true,
      meta_title: 'Flumeucil 600mg | Medicum Egypt',
      meta_description: 'Flumeucil effervescent for chest congestion.',
      tags: ['mucolytic', 'cough', 'chest-congestion', 'effervescent']
    },
    {
      product_code: 'MED-012-OTRI',
      sku: 'OTRI-01-10ML',
      barcode: '6221060003789',
      name_en: 'Otrivin Nasal Spray 0.1%',
      name_ar: 'أوتريفين بخاخ أنف 0.1%',
      description_en: 'Nasal decongestant spray for blocked nose.',
      description_ar: 'بخاخ مزيل لاحتقان الأنف.',
      category: 'cold-flu',
      subcategory: 'nasal-medications',
      brand: 'GSK',
      manufacturer: 'GlaxoSmithKline Egypt',
      country_of_origin: 'Egypt',
      price: 28.00,
      price_per_unit: 28.00,
      discount_percentage: 10,
      tax_percentage: 14,
      stock_quantity: 400,
      min_order_quantity: 1,
      max_order_quantity: 6,
      requires_prescription: false,
      active_ingredient: 'Xylometazoline HCl 0.1%',
      dosage_form: 'Nasal spray',
      side_effects: 'Burning sensation, dryness',
      contraindications: 'Children under 12, narrow-angle glaucoma',
      storage_conditions: 'Store below 30°C',
      delivery_method: 'express',
      delivery_days_min: 1,
      delivery_days_max: 2,
      delivery_fee: 35.00,
      image_url: 'https://via.placeholder.com/400x300/A8DADC/333333?text=Otrivin',
      product_images: ['https://via.placeholder.com/400x300/A8DADC/333333?text=Otrivin'],
      unit: 'bottle',
      unit_size: '10ml',
      unit_item: 'bottle',
      is_featured: false,
      is_active: true,
      in_stock: true,
      meta_title: 'Otrivin Nasal Spray | Medicum Egypt',
      meta_description: 'Otrivin nasal spray for congestion relief.',
      tags: ['nasal-spray', 'decongestant', 'blocked-nose', 'OTC']
    },
    // Adding remaining products (13-20)
    {
      product_code: 'MED-013-RANT',
      sku: 'RANT-150-20T',
      barcode: '6221060004123',
      name_en: 'Rantidine 150mg Tablets',
      name_ar: 'رانتيدين 150 مجم أقراص',
      description_en: 'For heartburn and acid reflux.',
      description_ar: 'لحرقة المعدة وارتجاع الحمض.',
      category: 'digestive',
      subcategory: 'oral-medications',
      brand: 'EIPICO',
      manufacturer: 'EIPICO Egypt',
      country_of_origin: 'Egypt',
      price: 22.00,
      price_per_unit: 22.00,
      discount_percentage: 15,
      tax_percentage: 14,
      stock_quantity: 350,
      min_order_quantity: 1,
      max_order_quantity: 8,
      requires_prescription: false,
      active_ingredient: 'Ranitidine HCl 150mg',
      dosage_form: 'Film-coated tablet',
      side_effects: 'Headache, dizziness, constipation',
      contraindications: 'Kidney disease, porphyria',
      storage_conditions: 'Store below 25°C',
      delivery_method: 'standard',
      delivery_days_min: 1,
      delivery_days_max: 3,
      delivery_fee: 30.00,
      image_url: 'https://via.placeholder.com/400x300/457B9D/FFFFFF?text=Rantidine',
      product_images: ['https://via.placeholder.com/400x300/457B9D/FFFFFF?text=Rantidine'],
      unit: 'box',
      unit_size: '20 tablets',
      unit_item: 'box',
      is_featured: false,
      is_active: true,
      in_stock: true,
      meta_title: 'Rantidine 150mg | Medicum Egypt',
      meta_description: 'Rantidine for heartburn and acid reflux.',
      tags: ['heartburn', 'acid-reflux', 'digestive', 'OTC']
    },
    {
      product_code: 'MED-014-LACT',
      sku: 'LACT-120ML',
      barcode: '6221060004456',
      name_en: 'Lactulose Syrup 667mg/ml',
      name_ar: 'لاكتيولوز شراب 667 مجم/مل',
      description_en: 'Gentle laxative for constipation relief.',
      description_ar: 'ملين لطيف لعلاج الإمساك.',
      category: 'digestive',
      subcategory: 'oral-medications',
      brand: 'Amriya',
      manufacturer: 'Amriya Pharmaceuticals',
      country_of_origin: 'Egypt',
      price: 18.00,
      price_per_unit: 18.00,
      discount_percentage: 10,
      tax_percentage: 14,
      stock_quantity: 250,
      min_order_quantity: 1,
      max_order_quantity: 6,
      requires_prescription: false,
      active_ingredient: 'Lactulose 667mg/ml',
      dosage_form: 'Syrup',
      side_effects: 'Bloating, gas, cramping',
      contraindications: 'Galactosemia, intestinal obstruction',
      storage_conditions: 'Store below 25°C, do not freeze',
      delivery_method: 'standard',
      delivery_days_min: 2,
      delivery_days_max: 3,
      delivery_fee: 30.00,
      image_url: 'https://via.placeholder.com/400x300/1D3557/FFFFFF?text=Lactulose',
      product_images: ['https://via.placeholder.com/400x300/1D3557/FFFFFF?text=Lactulose'],
      unit: 'bottle',
      unit_size: '120ml',
      unit_item: 'bottle',
      is_featured: false,
      is_active: true,
      in_stock: true,
      meta_title: 'Lactulose Syrup | Medicum Egypt',
      meta_description: 'Lactulose syrup for gentle constipation relief.',
      tags: ['laxative', 'constipation', 'digestive', 'OTC']
    },
    {
      product_code: 'MED-015-ENTE',
      sku: 'ENTE-10V',
      barcode: '6221060004789',
      name_en: 'Enterogermina Probiotic',
      name_ar: 'إنتيروجيرمينا بروبيوتيك',
      description_en: 'Probiotic for digestive balance.',
      description_ar: 'بروبيوتيك لتوازن الجهاز الهضمي.',
      category: 'digestive',
      subcategory: 'probiotics',
      brand: 'Sanofi',
      manufacturer: 'Sanofi Egypt',
      country_of_origin: 'Egypt',
      price: 75.00,
      price_per_unit: 75.00,
      discount_percentage: 5,
      tax_percentage: 14,
      stock_quantity: 150,
      min_order_quantity: 1,
      max_order_quantity: 5,
      requires_prescription: false,
      active_ingredient: 'Bacillus clausii 2 billion spores',
      dosage_form: 'Oral suspension',
      side_effects: 'Very rare: skin rash',
      contraindications: 'Immunodeficiency',
      storage_conditions: 'Store below 30°C',
      delivery_method: 'express',
      delivery_days_min: 1,
      delivery_days_max: 2,
      delivery_fee: 35.00,
      image_url: 'https://via.placeholder.com/400x300/F1FAEE/333333?text=Enterogermina',
      product_images: ['https://via.placeholder.com/400x300/F1FAEE/333333?text=Enterogermina'],
      unit: 'box',
      unit_size: '10 vials',
      unit_item: 'box',
      is_featured: true,
      is_active: true,
      in_stock: true,
      meta_title: 'Enterogermina Probiotic | Medicum Egypt',
      meta_description: 'Enterogermina probiotic for digestive health.',
      tags: ['probiotic', 'digestive-health', 'diarrhea', 'antibiotics']
    },
    {
      product_code: 'MED-016-GLUC',
      sku: 'GLUC-500-30T',
      barcode: '6221060005123',
      name_en: 'Glucophage 500mg Tablets',
      name_ar: 'جلوكوفاج 500 مجم أقراص',
      description_en: 'Metformin for type 2 diabetes.',
      description_ar: 'ميتفورمين لمرض السكري من النوع 2.',
      category: 'diabetes',
      subcategory: 'oral-medications',
      brand: 'Merck',
      manufacturer: 'Merck Egypt',
      country_of_origin: 'Egypt',
      price: 38.00,
      price_per_unit: 38.00,
      discount_percentage: 0,
      tax_percentage: 14,
      stock_quantity: 200,
      min_order_quantity: 1,
      max_order_quantity: 5,
      requires_prescription: true,
      active_ingredient: 'Metformin HCl 500mg',
      dosage_form: 'Film-coated tablet',
      side_effects: 'Nausea, diarrhea, stomach upset.',
      contraindications: 'Kidney disease, metabolic acidosis',
      storage_conditions: 'Store below 25°C',
      delivery_method: 'standard',
      delivery_days_min: 1,
      delivery_days_max: 3,
      delivery_fee: 30.00,
      image_url: 'https://via.placeholder.com/400x300/E63946/FFFFFF?text=Glucophage',
      product_images: ['https://via.placeholder.com/400x300/E63946/FFFFFF?text=Glucophage'],
      unit: 'box',
      unit_size: '30 tablets',
      unit_item: 'box',
      is_featured: false,
      is_active: true,
      in_stock: true,
      meta_title: 'Glucophage 500mg | Medicum Egypt',
      meta_description: 'Glucophage metformin for type 2 diabetes.',
      tags: ['diabetes', 'metformin', 'blood-sugar', 'prescription']
    },
    {
      product_code: 'MED-017-TEST',
      sku: 'TEST-GLU-50',
      barcode: '6221060005456',
      name_en: 'Blood Glucose Test Strips',
      name_ar: 'شرائط اختبار جلوكوز الدم',
      description_en: 'Accurate blood glucose test strips.',
      description_ar: 'شرائط دقيقة لاختبار جلوكوز الدم.',
      category: 'diabetes',
      subcategory: 'testing-supplies',
      brand: 'Accu-Chek',
      manufacturer: 'Roche Egypt',
      country_of_origin: 'Egypt',
      price: 120.00,
      price_per_unit: 120.00,
      discount_percentage: 10,
      tax_percentage: 14,
      stock_quantity: 300,
      min_order_quantity: 1,
      max_order_quantity: 10,
      requires_prescription: false,
      active_ingredient: 'N/A',
      dosage_form: 'Test strip',
      side_effects: 'N/A',
      contraindications: 'N/A',
      storage_conditions: 'Store in cool, dry place.',
      delivery_method: 'express',
      delivery_days_min: 1,
      delivery_days_max: 2,
      delivery_fee: 35.00,
      image_url: 'https://via.placeholder.com/400x300/F77F00/FFFFFF?text=Test+Strips',
      product_images: ['https://via.placeholder.com/400x300/F77F00/FFFFFF?text=Test+Strips'],
      unit: 'box',
      unit_size: '50 strips',
      unit_item: 'box',
      is_featured: true,
      is_active: true,
      in_stock: true,
      meta_title: 'Blood Glucose Test Strips | Medicum Egypt',
      meta_description: 'Accurate blood glucose test strips.',
      tags: ['diabetes', 'blood-glucose', 'test-strips', 'monitoring']
    },
    {
      product_code: 'MED-018-PANT',
      sku: 'PANT-SHA-400',
      barcode: '6221060005789',
      name_en: 'Pantene Pro-V Shampoo 400ml',
      name_ar: 'شامبو بانتين برو-في 400 مل',
      description_en: 'Nourishing shampoo for healthy hair.',
      description_ar: 'شامبو مغذي لشعر صحي ولامع.',
      category: 'personal-care',
      subcategory: 'hair-care',
      brand: 'Pantene',
      manufacturer: 'P&G Egypt',
      country_of_origin: 'Egypt',
      price: 65.00,
      price_per_unit: 65.00,
      discount_percentage: 20,
      tax_percentage: 14,
      stock_quantity: 200,
      min_order_quantity: 1,
      max_order_quantity: 6,
      requires_prescription: false,
      active_ingredient: 'Pro-Vitamin B5, Silk Protein',
      dosage_form: 'Shampoo',
      side_effects: 'Rare: scalp irritation',
      contraindications: 'Allergy to ingredients',
      storage_conditions: 'Store at room temperature',
      delivery_method: 'standard',
      delivery_days_min: 2,
      delivery_days_max: 3,
      delivery_fee: 30.00,
      image_url: 'https://via.placeholder.com/400x300/EAE2B7/333333?text=Pantene',
      product_images: ['https://via.placeholder.com/400x300/EAE2B7/333333?text=Pantene'],
      unit: 'bottle',
      unit_size: '400ml',
      unit_item: 'bottle',
      is_featured: false,
      is_active: true,
      in_stock: true,
      meta_title: 'Pantene Pro-V Shampoo | Medicum Egypt',
      meta_description: 'Pantene Pro-V nourishing shampoo.',
      tags: ['shampoo', 'hair-care', 'pantene', 'personal-care']
    },
    {
      product_code: 'MED-019-SENS',
      sku: 'SENS-75ML',
      barcode: '6221060006123',
      name_en: 'Sensodyne Toothpaste 75ml',
      name_ar: 'معجون أسنان سنسوداين 75 مل',
      description_en: 'Toothpaste for sensitive teeth.',
      description_ar: 'معجون أسنان للأسنان الحساسة.',
      category: 'personal-care',
      subcategory: 'oral-care',
      brand: 'Sensodyne',
      manufacturer: 'GSK Egypt',
      country_of_origin: 'Egypt',
      price: 45.00,
      price_per_unit: 45.00,
      discount_percentage: 15,
      tax_percentage: 14,
      stock_quantity: 350,
      min_order_quantity: 1,
      max_order_quantity: 8,
      requires_prescription: false,
      active_ingredient: 'Potassium Nitrate 5%, Sodium Fluoride 0.254%',
      dosage_form: 'Toothpaste',
      side_effects: 'N/A',
      contraindications: 'Children under 12 without supervision',
      storage_conditions: 'Store below 30°C',
      delivery_method: 'standard',
      delivery_days_min: 1,
      delivery_days_max: 3,
      delivery_fee: 30.00,
      image_url: 'https://via.placeholder.com/400x300/FCBAD3/333333?text=Sensodyne',
      product_images: ['https://via.placeholder.com/400x300/FCBAD3/333333?text=Sensodyne'],
      unit: 'tube',
      unit_size: '75ml',
      unit_item: 'tube',
      is_featured: false,
      is_active: true,
      in_stock: true,
      meta_title: 'Sensodyne Toothpaste | Medicum Egypt',
      meta_description: 'Sensodyne toothpaste for sensitive teeth.',
      tags: ['toothpaste', 'sensitive-teeth', 'oral-care', 'sensodyne']
    },
    {
      product_code: 'MED-020-DETT',
      sku: 'DETT-500ML',
      barcode: '6221060006456',
      name_en: 'Dettol Antiseptic Liquid 500ml',
      name_ar: 'سائل ديتول المطهر 500 مل',
      description_en: 'Multi-purpose antiseptic for wound cleaning.',
      description_ar: 'مطهر متعدد الأغراض لتنظيف الجروح.',
      category: 'personal-care',
      subcategory: 'antiseptics',
      brand: 'Dettol',
      manufacturer: 'Reckitt Egypt',
      country_of_origin: 'Egypt',
      price: 58.00,
      price_per_unit: 58.00,
      discount_percentage: 10,
      tax_percentage: 14,
      stock_quantity: 400,
      min_order_quantity: 1,
      max_order_quantity: 10,
      requires_prescription: false,
      active_ingredient: 'Chloroxylenol 4.8%',
      dosage_form: 'Liquid',
      side_effects: 'Skin irritation if undiluted',
      contraindications: 'Do not use undiluted on skin',
      storage_conditions: 'Store below 30°C',
      delivery_method: 'express',
      delivery_days_min: 1,
      delivery_days_max: 2,
      delivery_fee: 35.00,
      image_url: 'https://via.placeholder.com/400x300/003D5B/FFFFFF?text=Dettol',
      product_images: ['https://via.placeholder.com/400x300/003D5B/FFFFFF?text=Dettol'],
      unit: 'bottle',
      unit_size: '500ml',
      unit_item: 'bottle',
      is_featured: true,
      is_active: true,
      in_stock: true,
      meta_title: 'Dettol Antiseptic Liquid | Medicum Egypt',
      meta_description: 'Dettol antiseptic liquid for wound care.',
      tags: ['antiseptic', 'disinfectant', 'dettol', 'first-aid']
    }
  ];

  try {
    // Insert products into Supabase
    const response = await fetch(`${SUPABASE_URL}/rest/v1/products`, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'apikey': SUPABASE_SERVICE_KEY,
        'Authorization': `Bearer ${SUPABASE_SERVICE_KEY}`,
        'Prefer': 'return=minimal'
      },
      body: JSON.stringify(products)
    });

    if (response.ok) {
      console.log('✅ Products successfully loaded into Supabase!');
      return true;
    } else {
      const error = await response.text();
      console.error('❌ Failed to load products:', error);
      
      // If table doesn't exist, provide instructions
      if (error.includes('relation') && error.includes('does not exist')) {
        console.log('\n📝 The products table doesn\'t exist yet.');
        console.log('Please run the CREATE_TABLES_AND_IMPORT.sql script in Supabase SQL Editor first.');
      }
      return false;
    }
  } catch (error) {
    console.error('❌ Error loading products:', error.message);
    return false;
  }
}

async function verifyProducts() {
  console.log('\n🔍 Verifying loaded products...');
  
  try {
    const response = await fetch(`${SUPABASE_URL}/rest/v1/products?select=product_code,name_en,price&limit=5`, {
      headers: {
        'apikey': SUPABASE_SERVICE_KEY,
        'Authorization': `Bearer ${SUPABASE_SERVICE_KEY}`
      }
    });

    if (response.ok) {
      const products = await response.json();
      console.log(`\n✅ Found ${products.length} products in database:`);
      products.forEach(p => {
        console.log(`  - ${p.name_en}: EGP ${p.price}`);
      });
    } else {
      console.log('⚠️ Could not verify products');
    }
  } catch (error) {
    console.log('⚠️ Verification failed:', error.message);
  }
}

// Main execution
async function main() {
  console.log('🚀 Loading Products Data to Supabase');
  console.log('=====================================\n');
  
  // Try to create categories first
  await createTables();
  
  // Load products
  const success = await loadProducts();
  
  if (success) {
    // Verify the load
    await verifyProducts();
    
    console.log('\n🎉 Data loading complete!');
    console.log('📱 Products should now be visible in your application');
  } else {
    console.log('\n⚠️ Data loading failed. Please check the error messages above.');
  }
}

// Run the script
main();